# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gQ2AsqBOXFIVdf8vjf-TgswvoDm0L6kc

1. Realice un programa donde se soliciten dos números al usuario, después se de como resultado el residuo y el cociente de la división entre n1 y n2.
"""

D=int(input('Ingrese el dividendo: '))
d=int(input('Ingrese el divisor: '))
cociente=D/d
residuo=D%d
print('El cociente es: ',cociente)
print('El residuo es: ', residuo)

"""2. Realice un programa que calcule el índice de masa corporal de una persona, donde le solicite al usuario la estatura en cm y el peso en Kg. Después imprima como resultado el índice de masa corporal mediante un mensaje que diga “Su IMC es valor” redondeado con dos decimales. """

E=float(input('Ingrese su estatura en cm: '))
P=float(input('Ingrese su peso en Kg: '))
IdM=P/(E)**2
print('Su IMC es',round(IdM,2))

"""3. Realice un programa donde se solicite al usuario escribir el precio final de un artículo o producto, con el que después calculará e imprimirá en pantalla el valor del IVA y el valor bruto (precio antes de IVA) del artículo o producto. """

Precio_producto=int(input('Ingrese el precio final de su producto: '))
Aumento=Precio_producto*(19/100)
CI=Precio_producto+Aumento
print('El valor bruto es: ',Precio_producto)
print('El valor del producto con Iva es: ',CI )

"""4. Realice un programa que permita calcular el costo anual del consumo de combustible de un vehículo, si el usuario ingresa la distancia recorrida (Km) anual, el consumo de combustible (L / 100Km) anual y el costo promedio anual del combustible por litros recorridos ($ / L). """

Distancia=float(input('Ingrese la distancia recorrida anual en Km: '))
C_combustible=float(input('Ingrese el consumo de combustible anual (L/100Km): '))
Costo=float(input('Ingrese el costo promedio anual del combustible por litros recorridos ($ / L).: '))
Costo_anual=((Distancia/100)*C_combustible)*Costo
print('El costo anual del consumo de combustible de un vehiculo es de: ',Costo_anual)